# This workflow will install Python dependencies and update README.md

name: Auto-Update Files

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4
    - name: Set up mamba ${{ matrix.python-version }}
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: 'latest'
        environment-file: environment.yml
        init-shell: bash
        environment-name: tsutterley
        cache-environment: true
        post-cleanup: 'all'
        create-args: python=${{ matrix.python-version }}
    - name: Update README.md
      run: |
        python update_readme.py ${{ secrets.OPEN_WEATHER_API_KEY }}
    - name: Commit changes and push if changed
      run: |-
        git add .
        git diff
        git config user.name 'Github Actions'
        git config user.email 'actions@github.com'
        git commit -m "Automatic README.md update" -a || echo "No changes to commit"
        git push
